import React from 'react';

const ScreenOne = () => {
  return (
      <div className="bg-white text-black p-6">
            {/* Header */}
                  <div className="text-center">
                          <h2 className="text-3xl font-bold">Our Mission</h2>
                                  <p className="text-gray-600 mt-2">Lorem ipsum dolor sit amet...</p>

                                          <h2 className="text-3xl font-bold mt-8">Our Vision</h2>
                                                  <p className="text-gray-600 mt-2">Lorem ipsum dolor sit amet...</p>
                                                        </div>

                                                              {/* Milestones */}
                                                                    <div className="mt-12 text-center">
                                                                            <h2 className="text-3xl font-bold mb-6">Our Milestones</h2>
                                                                                    <div className="flex justify-center gap-6 flex-wrap">
                                                                                              {["2015 Founded", "100+ Projects", "500+ Clients", "2023 Leader"].map((text, i) => (
                                                                                                          <div key={i} className="bg-purple-600 text-white px-6 py-4 rounded-full shadow-md">
                                                                                                                        {text}
                                                                                                                                    </div>
                                                                                                                                              ))}
                                                                                                                                                      </div>
                                                                                                                                                            </div>

                                                                                                                                                                  {/* Team */}
                                                                                                                                                                        <div className="mt-16">
                                                                                                                                                                                <h2 className="text-center text-3xl font-bold">Our Team</h2>
                                                                                                                                                                                        <div className="flex justify-center gap-12 mt-8 flex-wrap">
                                                                                                                                                                                                  {[
                                                                                                                                                                                                              { name: "George Williams", role: "President Salam" },
                                                                                                                                                                                                                          { name: "Laura Sanchez", role: "Sales Expert" },
                                                                                                                                                                                                                                      { name: "Karen Smith", role: "President" },
                                                                                                                                                                                                                                                ].map((member, i) => (
                                                                                                                                                                                                                                                            <div key={i} className="text-center">
                                                                                                                                                                                                                                                                          <img src={`https://via.placeholder.com/150?text=${member.name.split(' ')[0]}`} className="mx-auto rounded-full mb-4" alt={member.name} />
                                                                                                                                                                                                                                                                                        <h4 className="font-semibold">{member.name}</h4>
                                                                                                                                                                                                                                                                                                      <p className="text-gray-500">{member.role}</p>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                {/* Core Values */}
                                                                                                                                                                                                                                                                                                                                                      <div className="mt-16 text-center">
                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-3xl font-bold mb-4">Our Core Values</h2>
                                                                                                                                                                                                                                                                                                                                                                      <div className="flex flex-wrap justify-center gap-6">
                                                                                                                                                                                                                                                                                                                                                                                {["Integrity", "Innovation", "Collaboration", "Quality", "Customer Focus", "Safety"].map((val, i) => (
                                                                                                                                                                                                                                                                                                                                                                                            <div key={i} className="flex flex-col items-center">
                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-2xl">✔️</div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <p>{val}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default ScreenOne;